import type { RegisterPalette } from "@/lib/register-palette"

// Hex mirrors of the design tokens, for the Open Graph card renderer only.
//
// WHY THIS FILE EXISTS. Every colour in the app goes through the oklch tokens
// generated by scripts/generate-register-tokens.mjs, and CI
// (scripts/check-hex-colors.mjs) blocks hex literals in app source. The one
// place that rule cannot reach is Satori — the rasteriser behind next/og —
// which draws from inline styles with no stylesheet, no CSS variables and no
// oklch support. So the share cards need the tokens' values as hex, and this
// is the single, allowlisted file that holds them.
//
// ONE MIRROR PER PALETTE (2026-08-31 — the register-palette rollout reaching
// the share cards): a memorial's link unfurls purple, a celebration's
// magenta, a fundraiser's green; neutral favpolls and the site card stay on
// the blue default. Values are computed from the generator's recipe (hue,
// chroma, primary lightness → the same oklch→sRGB maths) — re-tune a palette
// there, recompute these. `background` is shared: the cards are white.
export type OgPalette = {
  background: string
  foreground: string
  mutedForeground: string
  primary: string
  primaryMuted: string
  secondary: string
  borderStrong: string
  revealForeground: string
}

const WHITE = "#FFFFFF"

export const OG_PALETTES: Record<RegisterPalette | "default", OgPalette> = {
  /** Default — blue (h 252, c 0.15, pL 0.46) */
  default: {
    background: WHITE,
    foreground: "#11171D",
    mutedForeground: "#546B85",
    primary: "#0058A8",
    primaryMuted: "#4E89CA",
    secondary: "#E6F3FF",
    borderStrong: "#87B2E2",
    revealForeground: "#022C53",
  },
  /** Memorial — purple (h 278, c 0.18, pL 0.44) */
  memorial: {
    background: WHITE,
    foreground: "#14151F",
    mutedForeground: "#61668C",
    primary: "#423CB2",
    primaryMuted: "#747BD9",
    secondary: "#EDF0FF",
    borderStrong: "#9FA8ED",
    revealForeground: "#22225B",
  },
  /** Celebration — magenta (h 345, c 0.17, pL 0.5) */
  celebration: {
    background: WHITE,
    foreground: "#1C1318",
    mutedForeground: "#815C70",
    primary: "#A12D79",
    primaryMuted: "#BD6398",
    secondary: "#FFEBF6",
    borderStrong: "#D996BC",
    revealForeground: "#4A1236",
  },
  /** Fundraiser — green (h 160, c 0.13, pL 0.5) */
  fundraiser: {
    background: WHITE,
    foreground: "#101814",
    mutedForeground: "#537160",
    primary: "#007948",
    primaryMuted: "#479971",
    secondary: "#E6F7ED",
    borderStrong: "#86BD9E",
    revealForeground: "#00361E",
  },
}

/** The default mirror — the site card, emails-adjacent uses, tests. */
export const OG_PALETTE = OG_PALETTES.default
