export type Phase =
  | "arriving" // step 1
  | "selected" // step 2
  | "pledge-panel" // step 3
  | "amount-picked" // step 4
  | "pledging" // step 5
  | "confirmed" // step 5 (toast visible)
  | "clearing" // step 6
  | "reveal" // step 7–9

export type HeroScene = {
  occasion: string
  protagonistName: string
  protagonistInitials: string
  avatarColor: string
  topicTitle: string
  question: string
  options: { label: string }[]
  selectedIndex: number
  pledgeAmount: string
  charity: string
  revealLabel: string
  revealText: string
  barLabels: string[]
  barWidths: number[]
  barAmounts: string[]
  total: string
  totalLabel: string
}

export const SCENES: HeroScene[] = [
  {
    occasion: "Memorial",
    protagonistName: "Belinda Hartley",
    protagonistInitials: "BH",
    avatarColor: "#7F77DD",
    topicTitle: "Colour",
    question: "Belinda had a colour she always wore — do you?",
    options: [
      { label: "Black" },
      { label: "Blue" },
      { label: "Brown" },
      { label: "Gold" },
      { label: "Green" },
      { label: "Grey" },
      { label: "Orange" },
      { label: "Pink" },
      { label: "Purple" },
      { label: "Red" },
      { label: "Silver" },
      { label: "White" },
      { label: "Yellow" },
    ],
    selectedIndex: 1,
    pledgeAmount: "£10",
    charity: "Marie Curie",
    revealLabel: "Belinda's reveal",
    revealText: "Mine was purple. I wore it to every occasion that mattered.",
    barLabels: ["Purple", "Blue", "Red", "Green", "Pink", "Black"],
    barWidths: [78, 51, 38, 28, 21, 14],
    barAmounts: ["£350", "£220", "£165", "£120", "£90", "£60"],
    total: "£1,005",
    totalLabel: "raised for Marie Curie",
  },
  {
    occasion: "Birthday",
    protagonistName: "Poppy Chen",
    protagonistInitials: "PC",
    avatarColor: "#E87D6A",
    topicTitle: "Ice cream",
    question: "Tell us your favourite ice cream to find out Poppy's.",
    options: [
      { label: "Banana" },
      { label: "Blackcurrant" },
      { label: "Brown bread" },
      { label: "Bubblegum" },
      { label: "Butterscotch" },
      { label: "Cherry" },
      { label: "Chocolate" },
      { label: "Chocolate chip" },
      { label: "Clotted cream" },
      { label: "Coconut" },
      { label: "Coffee" },
      { label: "Cookies and cream" },
      { label: "Elderflower" },
      { label: "Honeycomb" },
      { label: "Mango" },
      { label: "Mint choc chip" },
      { label: "Neapolitan" },
      { label: "Peach" },
      { label: "Peanut butter" },
      { label: "Pistachio" },
      { label: "Raspberry ripple" },
      { label: "Rhubarb and custard" },
      { label: "Rocky road" },
      { label: "Rum and raisin" },
      { label: "Salted caramel" },
      { label: "Strawberry" },
      { label: "Tiramisu" },
      { label: "Toffee" },
      { label: "Toffee fudge" },
      { label: "Vanilla" },
      { label: "Violet" },
      { label: "White chocolate" },
    ],
    selectedIndex: 15,
    pledgeAmount: "£20",
    charity: "Great Ormond Street Hospital",
    revealLabel: "Poppy's reveal",
    revealText: "Mint choc chip, of course. What do you mean you didn't know?",
    barLabels: [
      "Vanilla",
      "Chocolate",
      "Strawberry",
      "Mint choc chip",
      "Salted caramel",
      "Pistachio",
    ],
    barWidths: [84, 71, 52, 38, 24, 14],
    barAmounts: ["£210", "£175", "£130", "£95", "£60", "£35"],
    total: "£705",
    totalLabel: "raised for Great Ormond Street Hospital",
  },
  {
    occasion: "Retirement",
    protagonistName: "Ros Turner",
    protagonistInitials: "RT",
    avatarColor: "#4AAB8A",
    topicTitle: "Season",
    question: "Which time of year do you love? Is it the same as Ros's?",
    options: [
      { label: "Autumn" },
      { label: "Spring" },
      { label: "Summer" },
      { label: "Winter" },
    ],
    selectedIndex: 2,
    pledgeAmount: "£50",
    charity: "The Woodland Trust",
    revealLabel: "Ros's reveal",
    revealText: "Autumn, always. Childhood memories of walking through leaves.",
    barLabels: ["Spring", "Summer", "Autumn", "Winter"],
    barWidths: [71, 48, 35, 18],
    barAmounts: ["£290", "£195", "£140", "£75"],
    total: "£700",
    totalLabel: "raised for The Woodland Trust",
  },
  {
    occasion: "Engagement",
    protagonistName: "Alex & Jordan",
    protagonistInitials: "AJ",
    avatarColor: "#D4936B",
    topicTitle: "Animal",
    question: "What's your favourite animal? Alex & Jordan have one...",
    options: [
      { label: "African elephant" },
      { label: "Arctic fox" },
      { label: "Barn owl" },
      { label: "Blue whale" },
      { label: "Bottlenose dolphin" },
      { label: "Cheetah" },
      { label: "Emperor penguin" },
      { label: "Flamingo" },
      { label: "Giant otter" },
      { label: "Giant panda" },
      { label: "Giraffe" },
      { label: "Golden eagle" },
      { label: "Gorilla" },
      { label: "Hare" },
      { label: "Hedgehog" },
      { label: "Humpback whale" },
      { label: "Jaguar" },
      { label: "Kingfisher" },
      { label: "Leopard" },
      { label: "Lion" },
      { label: "Manta ray" },
      { label: "Mountain gorilla" },
      { label: "Narwhal" },
      { label: "Octopus" },
      { label: "Orangutan" },
      { label: "Orca" },
      { label: "Peregrine falcon" },
      { label: "Polar bear" },
      { label: "Red fox" },
      { label: "Red panda" },
      { label: "Red squirrel" },
      { label: "Sea turtle" },
      { label: "Snow leopard" },
      { label: "Tiger" },
      { label: "Wolf" },
    ],
    selectedIndex: 4,
    pledgeAmount: "£20",
    charity: "WWF",
    revealLabel: "Alex & Jordan's reveal",
    revealText:
      "The giant panda. They met at a conservation centre in Chengdu. Did you really need to ask?",
    barLabels: [
      "Giant panda",
      "African elephant",
      "Bottlenose dolphin",
      "Snow leopard",
      "Sea turtle",
      "Tiger",
    ],
    barWidths: [74, 48, 38, 31, 22, 14],
    barAmounts: ["£310", "£200", "£160", "£130", "£90", "£60"],
    total: "£950",
    totalLabel: "raised for WWF",
  },
  {
    occasion: "Leaving do",
    protagonistName: "Dave Kowalski",
    protagonistInitials: "DK",
    avatarColor: "#534AB7",
    topicTitle: "Biscuit",
    question:
      "We've had eight years of Dave's opinions about biscuits, what about your opinion?",
    options: [
      { label: "Biscoff" },
      { label: "Bourbon" },
      { label: "Caramel wafer" },
      { label: "Chocolate digestive" },
      { label: "Chocolate Hobnob" },
      { label: "Club" },
      { label: "Custard cream" },
      { label: "Digestive" },
      { label: "Fig roll" },
      { label: "Fruit shortcake" },
      { label: "Garibaldi" },
      { label: "Ginger nut" },
      { label: "Hobnob" },
      { label: "Iced gem" },
      { label: "Jaffa Cake" },
      { label: "Jammy Dodger" },
      { label: "Leibniz" },
      { label: "Malted milk" },
      { label: "Maryland cookie" },
      { label: "Nice" },
      { label: "Oreo" },
      { label: "Party ring" },
      { label: "Penguin" },
      { label: "Pink wafer" },
      { label: "Rich Tea" },
      { label: "Shortbread" },
      { label: "Shortcake" },
      { label: "Tunnock's Tea Cake" },
      { label: "Viennese whirl" },
      { label: "Viscount" },
      { label: "Wagon Wheel" },
      { label: "Wafer" },
    ],
    selectedIndex: 7,
    pledgeAmount: "£10",
    charity: "Comic Relief",
    revealLabel: "Dave's reveal",
    revealText: "Bourbon. He kept a not-so-secret stash in his desk drawer",
    barLabels: [
      "Bourbon",
      "Digestive",
      "Hobnob",
      "Custard cream",
      "Shortbread",
      "Ginger nut",
    ],
    barWidths: [69, 54, 38, 28, 18, 11],
    barAmounts: ["£185", "£145", "£100", "£75", "£50", "£30"],
    total: "£585",
    totalLabel: "raised for Comic Relief",
  },
  {
    occasion: "Graduation",
    protagonistName: "James Okafor",
    protagonistInitials: "JO",
    avatarColor: "#5B9BD5",
    topicTitle: "Film",
    question:
      "James' favourite film was the reason he applied to study engineering — what's yours?",
    options: [
      { label: "2001: A Space Odyssey" },
      { label: "Alien" },
      { label: "Amadeus" },
      { label: "Apocalypse Now" },
      { label: "Back to the Future" },
      { label: "Blade Runner" },
      { label: "Casablanca" },
      { label: "City of God" },
      { label: "Dr. Strangelove" },
      { label: "E.T." },
      { label: "Eternal Sunshine of the Spotless Mind" },
      { label: "Fargo" },
      { label: "Forrest Gump" },
      { label: "Goodfellas" },
      { label: "It's a Wonderful Life" },
      { label: "Jurassic Park" },
      { label: "Lawrence of Arabia" },
      { label: "Leon" },
      { label: "Monty Python's Life of Brian" },
      { label: "No Country for Old Men" },
      { label: "Parasite" },
      { label: "Psycho" },
      { label: "Pulp Fiction" },
      { label: "Rear Window" },
      { label: "Schindler's List" },
      { label: "Singin' in the Rain" },
      { label: "Spirited Away" },
      { label: "The Godfather" },
      { label: "The Shawshank Redemption" },
      { label: "The Silence of the Lambs" },
      { label: "The Truman Show" },
      { label: "The Wizard of Oz" },
      { label: "Vertigo" },
      { label: "Whiplash" },
    ],
    selectedIndex: 12,
    pledgeAmount: "£20",
    charity: "The Prince's Trust",
    revealLabel: "James's reveal",
    revealText: "Jurassic Park",
    barLabels: [
      "The Shawshank Redemption",
      "Jurassic Park",
      "Forrest Gump",
      "The Godfather",
      "Pulp Fiction",
      "Back to the Future",
    ],
    barWidths: [72, 61, 48, 38, 28, 17],
    barAmounts: ["£280", "£240", "£185", "£150", "£110", "£65"],
    total: "£1,030",
    totalLabel: "raised for The Prince's Trust",
  },
]

export const OCCASION_CHIPS = SCENES.map((s, i) => ({
  label: s.occasion,
  index: i,
}))
export const PLEDGE_AMOUNTS = ["£5", "£10", "£20", "£50"]
export const SCENE_EYEBROWS = [
  "In memory of someone special",
  "On the birthday they'll always remember",
  "After a lifetime of good work",
  "For the yes that changes everything",
  "For the one who's moving on",
  "As they take their next step",
]
