import type {
  FavpollCategory,
  FavpollGrouping,
  FavpollSubject,
  Register,
} from "@favpoll/types"
import type { SceneKind } from "@/components/hero-demo-panel/scenes"
import { deriveRegister } from "@/lib/registers"

// Which of the four palettes a thing wears (2026-08-30 — the register-palette
// decision; the palettes themselves are generated by
// scripts/generate-register-tokens.mjs). Null is the blue default: neutral
// favpolls, and every surface that is not one favpoll's.
export type RegisterPalette = "memorial" | "celebration" | "fundraiser"

export function paletteForRegister(
  register: Register | null | undefined
): RegisterPalette | null {
  switch (register) {
    case "remembering":
      return "memorial"
    case "celebrating_one":
    case "celebrating_many":
      return "celebration"
    // A person's fundraiser and a faceless cause are one register, and
    // one colour: the money is the point of both.
    case "cause":
      return "fundraiser"
    default:
      return null
  }
}

export function paletteForFavpoll(favpoll: {
  category?: FavpollCategory | null
  grouping?: FavpollGrouping | null
  subject?: FavpollSubject | null
}): RegisterPalette | null {
  return paletteForRegister(
    deriveRegister(
      favpoll.category ?? null,
      favpoll.grouping ?? "individual",
      favpoll.subject ?? undefined
    )
  )
}

/** The demo scenes' visitor-facing kinds map the same way the registers do. */
export function paletteForSceneKind(kind: SceneKind): RegisterPalette {
  return kind === "memorial"
    ? "memorial"
    : kind === "celebration"
      ? "celebration"
      : "fundraiser"
}
